- name: "Create network for unbound"
  community.docker.docker_network:
    name: "{{ unbound_net }}"
    driver: bridge
    ipam_config: "{{ unbound_net_config }}"

- name: Append an unbound network to the pihele networks list
  set_fact:
    docker_pihole_networks: "{{ docker_pihole_networks + [{'name': unbound_net}]}}"
  when: docker_pihole_unbound

- name: Setup unbound container
  community.docker.docker_container:
    name: unbound
    image: mvance/unbound:latest
    networks:
      - name: "{{ unbound_net | default('bridge') }}"
        ipv4_address: "{{ unbound_ip }}"
    restart_policy: unless-stopped
    volumes:
      - /etc/unbound:/opt/unbound/etc/unbound/
